### ISSUE TITLE
[Feature Request] Introduce breaking changes only in major release

### ISSUE THREAD

**Issue by FRSgit** [javajawa/check-registry-for-image#7]
Hey!

As a fellow OSS author I'm really grateful for this package and I do not want to put a blame or anything, just give you this information, please do not take it as an attack on your work 🙏 

I wanted to share a case we've just encountered with this action. Tt seems that `v2` is now pointing to different commit than it was before: now, under `v2` the support for node < 20 is dropped. And because of that a dozen of workflows have failed today in our CI infrastructure at @vuestorefront as we're currently using node 18.20.x.

If I can propose something: it would be great to make such changes under new major tags in the future (so in a case like this - under `v3`). It'll help all of users to plan for the migration without services breaking unexpectedly 😅
And for us (at vuestorefront / Alokai) it's a lesson to use commit hashes when using github actions 😄 

For this release - IMO it would be good to revert `v2` tag to previous state and add new one under `v3`, but I leave it up to you!

Once again - thanks for the action and have a great day!

**Comment by javajawa** [comment]
My apologies! I have reverted the `v2` back to where it was ~16 hours ago.

**Comment by javajawa** [comment]
Right, `v2` has been restored (and additonally tagged as `v2.0` for reference.

The mainline docs have been updated in #8 to reference `@v3`, and that has been tagged as `v3` and `v3.0`.

My apologies for the inconvenience -- I'm too used to working in close ecosystems these days. Let me know if it's worth back-porting the improvements to error handling when the registry returns errors.

**Comment by FRSgit** [comment]
Thanks for the quick response and handling this situation!

IMO backporting is not needed - it's no regression really. We'll move to v3 once we get to node@20 (so, probably next quarter). Having to manage on v2 for ~3 months is totally acceptable and resolvable on our side (by upgrading) so IMO it's a non-issue for you 😄 

We'll check if the reverted action works now (already switched to commit hash, need to revert that 😅 ) and will give you a sign soon!

**Comment by FRSgit** [comment]
Seems to be working on our end, thank you!
